### ISSUE TITLE
Make it so that if no serial number present, RMA can still be created.

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#45]
I was trying to figure out how we can change the flow so that if there is no serial number in the case, an RMA can be created.
Currently – if there is no serial in the case it thinks that this is a printer serial number which already exists, and so you can’t then create an RMA as it already thinks there is one for the blank serial.

I had this situation yesterday: dealer has replaced some Dye films for various customers, now wants RMA to return them to us. So not one specific printer, it’s just a case for dye film only.
I had to use printer Dummy 4 in the serial number field to be able to create the RMA

This is where I have been looking:
https://ultracardsystems.my.salesforce.com/designer/designer.apexp#Id=301d0000000LA08AAG

…But not sure how to add something along the lines of:   “if serial equals null/blank (?), then create RMA anyway” ?

![flow](https://cloud.githubusercontent.com/assets/8257794/5721153/e1cebd90-9b25-11e4-9d08-809c4f8d353e.jpg)

 

What do you think???

Or – we could create a printer called.. Dye Film???!!

**Comment by ChrisPellegrino** [comment]
i'll take a look at it. we need a little more logic in there.

**Comment by ChrisPellegrino** [comment]
Ok there are three ways we can go here.  

1)We can just do as you said dye film as a serial number. This will always work because of what we did in december. multiple rmas that are not printer ones. since dye film should never be a printer rma then it would work. we could just do generic dye film or the types like ma300 ,ma250 etc . this does not really matter though. 

2) We could also just use "Unknown"  this will work as well. in fact i could just set the default for the feild  printer serial to "unknown". That way no one has to think about it. but if you try to do a printer rma with "unknown" it will error. this can be done in the flow easily. 

3) in the flow we make a decision if serial number is null then go to this step and if not null go here.
the problem with this is the record require something in the serial field. It will error when creating other records so we would go to a page that lets you select something to put in there like unknown,dye film, etc... 

i'm leaning towards number 2 mainly because that is actually correct. we don't know it. it also makes sense on other records were the printer serial number is like the rma record and exchange record. 

it would say printer serial number : unknown  and not

Printer serial number: Dye film. 

What do you think ??? let me know.

**Comment by UltraIDTechnicalSupport** [comment]
Following phone call last night: yep. If serial is left blank it get set to not known yet / unknown.

Let me know when you are going to make it live and I will explain it to the chaps here..

:-)
[Luke]

**Comment by ChrisPellegrino** [comment]
Damn it!! I ran into the same original problem that we had. RMA Record as Repair and Eval are the same record type. 

I'm going to have to split them. Repair should be just for printers/lams  and eval should be for printheads,Dye films, or any other thing that is not a printer that we want sent in.  i can get it to work on everything else but that. Maybe i can think of a way to seprate them more.. hmmmm

**Comment by UltraIDTechnicalSupport** [comment]
Doh!

**Comment by UltraIDTechnicalSupport** [comment]
Muffadal came across this too:
Had a RECEIVED RMA for PCB.  Needed to create new RMA for Printhead, but it said "a received RMA already exists for this printers serial number".

I set this PCB RMA to Closed so he can do the new printhead one.

But I think this is the same thing you are working on resolving anyway...
I had a look at the flow again... be interested to see Repair and Eval seperated!!

[Luke]

**Comment by ChrisPellegrino** [comment]
i turns out i did not need to separate them. But i'm planing on to. I did not put in a prevision for an RTS part received. I did not think of that. I just put a prevision in the flow for that and will activate it and test it tomorrow and launch it.
