### ISSUE TITLE
Changes to Muffadal's Service Cloud setup...

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#49]
Hey Chris,

There are some things I (we !) could do to improve things for Muffadal... but I wondered if there is a quick way of doing it: although I expect not..

 - I think I need to remake (or clone) all the RMA stuff (rules emails etc) like I have done for UK.
I could email it to him directly, then he can just print stuff off from his email (rather the email-to-print).

 - I just teamviewered into him as he was having the multiple rma fever!
Once he has 'received' an RMA, he does not have the button to do a repair/eval. Maybe this doesn't matter???  But should we get him set up to do a repair process like we do here?
I added him the button in for 'Start repair/eval' and tested it.. but it did not change the RMA status to closed, and with it still set to Received he is unable to issue a new RMA!
He doesn't do it very often, so no biggy... but I think we should get the process at least similar to everywhere else - in the spirit of a "global System"

__________________________________________
Just wanted to create the GitHub to get it noted...

I am happy to plod through the work when I get chance.
Just wondering if you have any top tips for speeding it up!?

Once we get Muffadal all sorted, we can use this as a base for Johnson too...?

Ta.
[Luke]

**Comment by ChrisPellegrino** [comment]
A couple of things. If the RMA is a RTS Part ( thats the record ) there is no need for the repair eval button on that page layout. We do not Repair RTS parts. I took it off that page again. 
The repair eval button should be on the repair eval record layout and the RTS printer record layout. 

you can clone the rma stuff  I believe you only need to do the ones that are separated ....ie that have (UK)  Make a new one/ clone and change it to (DUB) so we can tell. You should notice in some of them it calls out the warehouse.  His warehouse is just Dubai.  if he does not want to use email to print then just push those to his email. If he wants he could push them to the contact but in that case you would want to change all the verbiage in the outgoing email template to reflect that. EEeeeeewwww!

By the way i did some research and HP email to print has issues like you describe having ( long wait times or not printing). If moving it to ethernet cable and doing the updates did not help. Try resetting/ wipe the web services and creating a new email. I did that at the US and have not had a problem since. If that does not help then i would recommend using either brother or epson.

**Comment by UltraIDTechnicalSupport** [comment]
Thanks Chris :)

- Button - OK, I get it.  I did forget to remove the button actually! Thanks for removing it.
So I think Muffadal can just set these RMA's to closed manually then - i the dropdown that now seems to work, it didnt work before I logged in?

- Yeah, thats what I thought... I can just manually go through and make a Dubai version of all the rma stuff...

- After I got back from visiting you, we moved the HP printer and put it on a wired connection -- It works flawlessly now :)
I had written this in a long email I gradually added to bit by bit as I worked on stuff we had discussed when I got back.. but after a month I had still not sent the email and I deleted it!! haha... sorry..  Then it slipped my mind.  So it was our crappy wireless network all along..  We had asked IT to wire it before.. in the end Alan had a cable so we just plugged it in and its perfect now...


So, I will gradually work on getting Muffadal's RMA's like ours.. I may also create similar ready for Johnson too.

Thanks again Captain Chris!
[Luke]

**Comment by ChrisPellegrino** [comment]
Im not sure. You have admin rights so you can change status. Muffadal does not so he should just use the receive button. I'm unlocking the button so anyone can use it. Not just warehouse profiles.
Good to here the printer is working fine now.

**Comment by UltraIDTechnicalSupport** [comment]
Closing this one.
Just finalizing Muffadal's setup regarding RMA's and exchanges, etc,.
