### ISSUE TITLE
Authoris(z)e the SF 'sent from' email address in HP ePrint?

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#57]
Hi Chris..
Just a quickie, and no problem if not possible..

Sometimes we have to wait a randomly long amount of time for the ‘Print Paperwork | Ready to Ship’ emails to print..
(Note.. its NOT related to the network here, we fixed this previous similar issue after we put it on a network cable like you said, that worked amazingly well!)

The ePrint side works fine.
The slow bit is the email from SF to ePrint. (I have sat refreshing the ePrint page and as soon the email gets in there, it prints fine)

So, my question is:
Can you Authorise the SF email from which the templates are sent from??
I don’t know where, or even if the ePrint authorisation email will be received, to be able to click the authorise link??

 
![image](https://cloud.githubusercontent.com/assets/8257794/8720469/d27849d6-2baa-11e5-8fa0-0250bf87c336.png)

I just wondered if we could authorise the email address, it may speed it up a bit??

**Comment by ChrisPellegrino** [comment]
all the emails to the hp are sent from notifications@ultraid.com. 

I know it is not sales-force because i pointed the workflow rule to me and i get it in less than a second. I think it is more the email print server hp uses.  i can see th notifications email box. if you want to resend the confirmation. Just just have to let me know as soon as you do it. I dont even use that manage addresses. I have mine wide open to everyone. I have noticed it getting slow or slower lately as well. My guess is that we need to use a different printer like epson or brother. perhaps they have a better email servers. I bet HP just gets slammed with emails to print.

**Comment by UltraIDTechnicalSupport** [comment]
Hmmm... well if I test it from my email, or support email the HP stuff is actually pretty good.
It just seemed to be the templates getting out of SF... 

So its likely those getting INTO HP thats the bottle neck..  yeah..

Think we have to live with it then :)

Cheers Chris.

Go Gals!
 
![image](https://cloud.githubusercontent.com/assets/8257794/8727498/f97b128e-2bd7-11e5-8c22-a5e78b2b795d.png)

**Comment by ChrisPellegrino** [comment]
The bottle neck is likely HP server. I was going to try a different printer though. Then we will know for sure. there is something going on just really hard to figure. Everytime i look into this all sides are ok. if you would like to have the emails sent to you just go to the uk workflow rules and add your email in the addtional. if you get the email but the printer does not print then i figure it is the hp email server.
