### ISSUE TITLE
OP / Quote creation | Duplicates the first repair option selected

### ISSUE THREAD

**Issue by UltraIDTechnicalSupport** [UltraID/Salesforce---ServiceCloud#61]
Hello Chris,

help...

Darren created a quote  (in europe rather than UK, maybe that's a clue???) for Minor Repair & Printhead.  But, the OP shows 2 Minor repairs, He deleted it all and tried again but same issue...
We cant get it to show the printhead..
(We also get 2 of the contact in there.. even if we untick the bill service to dealer button)

![image](https://cloud.githubusercontent.com/assets/8257794/11121951/a10bc8ba-8950-11e5-951d-74d6ee53ca96.png)

RMA-0004102:
https://ultracardsystems.my.salesforce.com/a0Vd000000D63YY

OP-006319:
https://ultracardsystems.my.salesforce.com/006d000000bHcHg?srPos=0&srKp=006

I think its all done in the Cost Estimate Flow?  But I didnt want to dick around in there and screw you guys over!!
https://ultracardsystems.my.salesforce.com/designer/designer.apexp#Id=301d0000000LHtyAAG

Cheers Chris...

**Comment by ChrisPellegrino** [comment]
ok the problem here is that the printhead-add does not have a euro dollar amount so it fails.i'm going to bed right now but it is an easy fix. 

luke or mike has to do this probably on there account.  go to products object do a search on printhead
you will get a list of the products with printhead.  
look in each Printhead Replace - add   some of the Printhead Replace -add's do not have a euro amount for pricing.  while in one of them just click ADD button just above the pricing and enter in the msrp euro amount.  by the way the second to the last one is the enduro + . If you feel motivated do all the ones missing.





open each one and if there is no euro amount add one

**Comment by UltraIDTechnicalSupport** [comment]
From: Luke Ridgway 
Sent: 13 November 2015 08:44
To: Darren Garbett; 'Chris Pellegrino'
Subject: OP / Quote creation | Duplicates the first repair option selected (#61)

Morning Darren & Chris…

This looks good now..
I followed what Chris said.. he was spot on: there was no Euro price some of the Printhead Replace –Add .. things.

I have added these to Enduro+ and Prima 4 (which had no prices in there at all???).
Didn’t bother with Alto, Opera, or Rio 2. 

I deleted the OP’s that where there from yesterday and from Chris testing it.  Created it again and all looks good.
Still got 2 Contacts in there? Bjorn de Roos.  But don’t think this will matter for getting this quote out..
I wonder if this is why he is there twice:  in the RMA, secondary email
 

_____________

RMA-0004102:
https://ultracardsystems.my.salesforce.com/a0Vd000000D63YY

OP-006333
https://ultracardsystems.my.salesforce.com/006d000000bHjYF

_____________

Chris, thanks again.. and well spotted.  Looks like you must have been working from home then to fix this..?!

Still goes to a blank screen after the quote is created successfully page:
https://ultracardsystems--c.na14.visual.force.com/apex/closePage


Best regards,

Luke Ridgway
